FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git build-base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /auth-server .

FROM alpine:latest

COPY --from=builder /auth-server /auth-server

EXPOSE 18080

CMD ["/auth-server"]