apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-middleware
  namespace: default
spec:
  cors:
    allowOrigin: "https://himatsumu.kirimaru.org"
    allowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowHeaders:
      - "Content-Type"
      - "Authorization"
    allowCredentials: true