apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-cors-middleware@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: auth-himatsumu.kirimaru.org
    http:
      paths:
      - backend:
          service:
            name: auth-service
            port:
              number: 18080
        path: /
        pathType: Prefix