name: Auth Service CI/CD

on:
    push:
        branches:
            - 'main'

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        outputs:
            IMAGE_NAME: ${{ steps.prepare_name.outputs.IMAGE_NAME }}
        name: Build and Push Docker Image

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Prepare image name
              id: prepare_name
              run: echo "IMAGE_NAME=$(echo ${{ github.repository}} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

            - name: Login to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile.prod
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ steps.prepare_name.outputs.IMAGE_NAME }}:latest
                      ${{ env.REGISTRY }}/${{ steps.prepare_name.outputs.IMAGE_NAME }}:${{ github.sha }}

    deploy:
        needs: build-and-push
        runs-on: self-hosted
        steps:
            - name: Deploy to K8s
              run: |
                  kubectl set image deployment/auth-service auth-container=${{ env.REGISTRY }}/${{ needs.build-and-push.outputs.IMAGE_NAME }}:${{ github.sha }}
                  kubectl rollout status deployment/auth-service